import React from 'react'

const Terms = () => {
  return (
    <div className=' mx-auto pt-[10rem] px-10 p-8 sm:px-6 lg:px-8'>
      <h1 className='text-3xl font-extrabold text-gray-900'>
        Terms and Conditions
      </h1>
      <p className='mt-4 text-gray-500'>
        Welcome to the Ndembele Crowd Farming Service Platform ("the Platform").
        This Platform is owned and operated by Hero Technologies, LLC, a US
        registered company with its registered office at Montana. We operate
        with nationally registered partners in every country where we are
        present. These Terms of Service govern your access to and use of the
        Platform and any associated services provided by us. By accessing or
        using the Platform, you agree to be bound by these Terms of Service. If
        you do not agree to these Terms of Service, you may not use the
        Platform.
      </p>
      <h2 className='text-2xl font-bold mt-8'>1. Use of the Platform</h2>
      <p className='mt-4 text-gray-500'>
        1.1. Eligibility: To use the Platform, you must be at least 18 years old
        (or legally able to enter into a contract in your jurisdiction). By
        using the Platform, you represent and warrant that you are eligible to
        use the Platform.
      </p>
      <p className='mt-4 text-gray-500'>
        1.2. Registration: To use certain features of the Platform, you may need
        to create an account and provide certain personal information. You agree
        to provide accurate, current, and complete information when creating an
        account, and to update your account information as necessary. You are
        solely responsible for the activity that occurs on your account.
      </p>
      <p className='mt-4 text-gray-500'>
        1.3. Prohibited Conduct: You agree not to use the Platform for any
        illegal or unauthorized purpose, and not to engage in any activity that
        violates these Terms of Service or any applicable laws. Prohibited
        conduct includes, but is not limited to:
      </p>
      <ul className='list-disc list-inside mt-2 text-gray-500'>
        <li>Harassing or intimidating other users</li>
        <li>
          Posting or transmitting false, inaccurate, or misleading information
        </li>
        <li>Impersonating another person or entity</li>
        <li>
          Interfering with or disrupting the Platform or its servers or networks
        </li>
        <li>Uploading or transmitting viruses, worms, or other harmful code</li>
      </ul>
      <p className='mt-4 text-gray-500'>
        1.4. Termination: We reserve the right to terminate or suspend your
        access to the Platform, without notice and without liability, for any
        reason, including but not limited to a violation of these Terms of
        Service.
      </p>
      <h2 className='text-2xl font-bold mt-8'>2. Crowd Farming Services</h2>
      <p className='mt-4 text-gray-500'>
        2.1. Crowd Farming: The Platform allows users to invest in agricultural
        projects and to participate in the profits generated by those projects.
        We make no representations or warranties about the quality, safety, or
        legality of the projects offered on the Platform.
      </p>
      <p className='mt-4 text-gray-500'>
        2.2. Investment Terms: Each project will have its own investment terms,
        including the amount of the investment required, the expected return,
        and the duration of the project. By investing in a project, you agree to
        the investment terms of that project.
      </p>
      <p className='mt-4 text-gray-500'>
        2.3. Returns: We make no guarantees or representations about the returns
        that may be generated by a project, and we are not responsible for any
        losses that may be incurred.
      </p>
      <p className='mt-4 text-gray-500'>
        2.4. Risks: Investing in agricultural projects involves risks, including
        the risk of loss of the invested capital. You should carefully consider
        the risks before investing in a project.
      </p>

      <h2 className='text-2xl font-bold mt-8'>3. Intellectual Property</h2>
      <p className='mt-4 text-gray-500'>
        3.1. Ownership: The Platform and its content, including but not limited
        to text, graphics, logos, and software, are the property of [Company
        Name] or its licensors and are protected by intellectual property laws.
      </p>
      <p className='mt-4 text-gray-500'>
        3.2. Use: You may use the Platform and its content only for the purposes
        permitted by these Terms of Service. You may not copy, modify,
        distribute, sell, or otherwise exploit any part of the Platform or its
        content without our prior written consent.
      </p>

      <h2 className='text-2xl font-bold mt-8'>Disclaimer of Warranties</h2>
      <p className='mt-4 text-gray-500'>
        THE PLATFORM AND ITS CONTENT ARE PROVIDED "AS IS" AND WITHOUT WARRANTY
        OF ANY KIND, WHETHER EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES,
        INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR
        A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE
        PLATFORM WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE
        CORRECTED, OR THAT THE PLATFORM OR ITS SERVERS ARE FREE OF VIRUSES OR
        OTHER HARMFUL COMPONENT
      </p>
    </div>
  )
}

export default Terms
